const javascriptQuestions = [
  { question: "Which company developed JavaScript?", options: ["Netscape", "Microsoft", "Google", "Oracle"], answer: "Netscape" },
  { question: "Which symbol is used for comments in JavaScript?", options: ["#", "//", "<!-- -->", "/* */"], answer: "//" },
  { question: "What will `typeof null` return in JavaScript?", options: ["null", "object", "undefined", "number"], answer: "object" },
  { question: "Which of the following is NOT a primitive data type in JavaScript?", options: ["String", "Number", "Boolean", "Array"], answer: "Array" },
  { question: "How can you create an array in JavaScript?", options: ["var arr = {}", "var arr = []", "var arr = ()", "var arr = <>"], answer: "var arr = []" },
  { question: "Which method converts JSON to a JavaScript object?", options: ["JSON.parse()", "JSON.stringify()", "JSON.objectify()", "JSON.convert()"], answer: "JSON.parse()" },
  { question: "What is the result of `2 + '2'` in JavaScript?", options: ["4", "22", "'4'", "NaN"], answer: "22" },
  { question: "Which keyword declares a constant in JavaScript?", options: ["const", "let", "var", "constant"], answer: "const" },
  { question: "What is a closure in JavaScript?", options: ["Function inside function with access to outer scope", "Loop function", "Function with class", "Arrow function"], answer: "Function inside function with access to outer scope" },
  { question: "Which method adds one or more elements to the end of an array?", options: ["push()", "pop()", "shift()", "unshift()"], answer: "push()" },
  { question: "How do you write an arrow function?", options: ["function => ()", "() => {}", "()=>function", "function->()"], answer: "() => {}" },
  { question: "What does `isNaN()` do?", options: ["Checks if value is not a number", "Checks if value is null", "Checks if value is string", "Checks if array"], answer: "Checks if value is not a number" },
  { question: "What is the output of `typeof NaN`?", options: ["number", "NaN", "undefined", "object"], answer: "number" },
  { question: "Which method removes the last element from an array?", options: ["pop()", "shift()", "unshift()", "remove()"], answer: "pop()" },
  { question: "What is the scope of a variable declared with var?", options: ["Function", "Block", "Global", "Module"], answer: "Function" },
  { question: "What keyword is used to create a class in JavaScript?", options: ["class", "object", "function", "constructor"], answer: "class" },
  { question: "Which of the following is a falsy value?", options: ["0", "1", "'false'", "[]"], answer: "0" },
  { question: "What is the result of `true + false`?", options: ["1", "truefalse", "NaN", "0"], answer: "1" },
  { question: "What is the correct syntax to import a module?", options: ["import x from 'x'", "require('x')", "import x = require('x')", "load('x')"], answer: "import x from 'x'" },
  { question: "Which symbol is used to spread elements in an array?", options: ["...", "@@", "::", "==="], answer: "..." },
  { question: "What is hoisting in JavaScript?", options: ["Moving declarations to top", "Looping data", "Memory leak", "Shadowing variable"], answer: "Moving declarations to top" },
  { question: "What is the use of `this` keyword?", options: ["Refers to current object", "Refers to global object", "Refers to child class", "None"], answer: "Refers to current object" },
  { question: "Which method removes the first element from an array?", options: ["shift()", "pop()", "push()", "slice()"], answer: "shift()" },
  { question: "What does the `map()` method do?", options: ["Creates a new array", "Changes existing array", "Filters array", "Removes values"], answer: "Creates a new array" },
  { question: "How do you define a default parameter?", options: ["function(x = 5)", "function(x: 5)", "function x{5}", "let x = 5"], answer: "function(x = 5)" },
  { question: "What does the `filter()` method do?", options: ["Returns array elements that pass a test", "Removes undefined", "Sorts array", "None"], answer: "Returns array elements that pass a test" },
  { question: "How can you delay execution in JavaScript?", options: ["setTimeout()", "delay()", "sleep()", "wait()"], answer: "setTimeout()" },
  { question: "What is the default value of `undefined`?", options: ["undefined", "null", "0", "''"], answer: "undefined" },
  { question: "What does `===` compare?", options: ["Value and type", "Only value", "Only type", "Nothing"], answer: "Value and type" },
  { question: "What is the purpose of `try...catch`?", options: ["Error handling", "Loop", "Import", "Class creation"], answer: "Error handling" },
  { question: "What is the output of `[] + []`?", options: ["''", "[]", "undefined", "NaN"], answer: "''" },
  { question: "Which built-in method returns the characters in a string beginning at the specified location?", options: ["substr()", "getCharAt()", "slice()", "charAt()"], answer: "slice()" },
  { question: "What is an Immediately Invoked Function Expression (IIFE)?", options: ["A function that runs immediately", "A loop", "A class", "A delay function"], answer: "A function that runs immediately" },
  { question: "Which statement is used to stop a loop?", options: ["break", "stop", "exit", "return"], answer: "break" },
  { question: "Which method returns the index of the first occurrence?", options: ["indexOf()", "find()", "locate()", "search()"], answer: "indexOf()" },
  { question: "Which function sorts array elements?", options: ["sort()", "order()", "arrange()", "set()"], answer: "sort()" },
  { question: "What does DOM stand for?", options: ["Document Object Model", "Data Object Model", "Digital Object Model", "Display Object Management"], answer: "Document Object Model" },
  { question: "Which method joins array elements into a string?", options: ["join()", "toString()", "concat()", "combine()"], answer: "join()" },
  { question: "How to comment multiple lines in JS?", options: ["/* */", "<!-- -->", "#", "** **"], answer: "/* */" },
  { question: "What is event bubbling?", options: ["Event propagation from child to parent", "Data handling", "Script loading", "Object merging"], answer: "Event propagation from child to parent" },
  { question: "How can you convert a string to number?", options: ["Number()", "int()", "parse()", "float()"], answer: "Number()" },
  { question: "What is the purpose of `localStorage`?", options: ["Store data locally", "Store session", "Store cookies", "Upload files"], answer: "Store data locally" },
  { question: "What is a Promise?", options: ["An object representing eventual completion", "A variable", "An event", "None"], answer: "An object representing eventual completion" },
  { question: "Which method executes a function for each array element?", options: ["forEach()", "map()", "filter()", "every()"], answer: "forEach()" },
  { question: "What is NaN?", options: ["Not a Number", "A string", "Null", "Negative"], answer: "Not a Number" },
  { question: "What keyword is used to declare variables?", options: ["var", "let", "const", "All of the above"], answer: "All of the above" },
  { question: "Which method is used to create new object with prototype?", options: ["Object.create()", "Object.new()", "Object.clone()", "NewObject()"], answer: "Object.create()" },
  { question: "How do you write an if condition?", options: ["if(x > 5) {}", "if x > 5 then", "if: x > 5 {}", "if > 5 then {}"], answer: "if(x > 5) {}" },
  { question: "Which operator is used for logical OR?", options: ["||", "&&", "!=", "=="], answer: "||" }
];

export default javascriptQuestions;